set -g window-status-separator " "
set -g window-status-format "#[fg=#{@thm_overlay_0},bg=default,none]#I #{b:pane_current_path}"
set -g window-status-current-format "#[fg=#{@thm_fg},bg=default,us=#{@thm_blue},underscore]#I #{b:pane_current_path}#[nounderscore]"
