# MIT License
#
# Copyright (c) 2025 Andrew Vasilyev <me@retran.me>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# @file: components/starship-config/starship.toml
# @brief: Starship prompt configuration
# @author: Andrew Vasilyev
# @license: MIT
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

command_timeout = 1000
scan_timeout = 100

format = """
$os\
$shlvl\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$lua\
$python\
$mise\
$docker_context\
$container\
$jobs\
$cmd_duration\
$status\
$line_break\
$character\
"""

palette = 'catppuccin_mocha'

[palettes.default]

color_ok = 'bright-green'
color_danger = 'bright-red'
color_caution = 'bright-yellow'

color_os = 'red'
color_username = 'red'
color_directory = 'yellow'
color_git = 'cyan'
color_git_added = 'bright-green'
color_git_deleted = 'bright-red'
color_env = 'blue'
color_kubernetes = 'purple'
color_docker = 'blue'
color_shell = ''
color_container = ''
color_other = ''
color_time = ''
color_duration = ''

color_vimcmd_ok = 'green'
color_vimcmd_replace = 'purple'
color_vimcmd_visual = 'yellow'

[palettes.catppuccin_mocha]

color_ok = '#a6e3a1'
color_danger = '#f38ba8'
color_caution = '#f9e2af'

color_os = '#f38ba8'
color_username = '#f38ba8'
color_directory = '#f9e2af'
color_git = '#89dceb'
color_git_added = '#a6e3a1'
color_git_deleted = '#f38ba8'
color_env = '#89b4fa'
color_kubernetes = '#cba6f7'
color_docker = '#89b4fa'
color_shell = '#cdd6f4'
color_container = '#f38ba8'
color_other = '#bac2de'
color_time = '#cdd6f4'
color_duration = '#cdd6f4'

color_vimcmd_ok = '#a6e3a1'
color_vimcmd_replace = '#cba6f7'
color_vimcmd_visual = '#f9e2af'

[os]
disabled = false
style = "fg:color_os"
format = '[$symbol]($style)'
[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = false
style_user = "fg:color_username"
style_root = "bold fg:color_danger"
format = '[ $user ]($style)'

[directory]
style = "fg:color_directory"
read_only_style = "fg:color_directory"
repo_root_style = "bold fg:color_directory"
format = "[ $path ]($style)"
repo_root_format = "[ $before_root_path]($style)[$repo_root]($repo_root_style)[$path ]($style)"
read_only = " "
home_symbol = "~"
truncation_symbol = " …/"
truncation_length = 4
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true

[git_branch]
symbol = ""
style = "fg:color_git"
format = '( [$symbol $branch]($style) )'
only_attached = true
ignore_branches = []
truncation_length = 25
truncation_symbol = "..."
always_show_remote = false
disabled = false

[git_commit]
style = "fg:color_git"
format = "( [($tag)(@$hash)]($style) )"
commit_hash_length = 7
only_detached = true
tag_symbol = "󰓼 "
tag_disabled = false
disabled = false

[git_status]
disabled = true

[git_metrics]
disabled = true

[git_state]
style = "fg:color_danger"
format = '([$state( $progress_current/$progress_total)]($style bold) )'
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
disabled = false

[nodejs]
symbol = ""
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[c]
symbol = ""
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[rust]
symbol = "󱘗"
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[golang]
symbol = "󰟓"
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[php]
symbol = ""
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[java]
symbol = ""
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[kotlin]
symbol = ""
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[haskell]
symbol = ""
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[lua]
symbol = "󰢱"
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[shlvl]
symbol = "󰘧"
style = "fg:color_caution"
format = '( [$symbol$shlvl]($style) )'
threshold = 2
disabled = false

[python]
symbol = ""
style = "fg:color_env"
format = '( [$symbol( $version)( $virtualenv)]($style) )'
version_format = '${major}.${minor}'

[mise]
symbol = "󱁤"
style = "fg:color_env"
format = '( [$symbol $version]($style) )'
detect_files = [".mise.toml", "mise.toml"]
disabled = false

[package]
disabled = true

[docker_context]
symbol = ""
style = "fg:color_docker"
format = '( [$symbol( $context)]($style) )'
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile", ".dockerignore"]
detect_extensions = []
detect_folders = []

[kubernetes]
disabled = true

[shell]
disabled = true
format = '[  $indicator ]($style)'
bash_indicator = "bash"
fish_indicator = "fish"
zsh_indicator = "zsh"
powershell_indicator = "powershell"
pwsh_indicator = "pwsh"
ion_indicator = "ion"
elvish_indicator = "elvish"
tcsh_indicator = "tcsh"
xonsh_indicator = "xonsh"
cmd_indicator = "cmd"
nu_indicator = "nu"
unknown_indicator = ""
style = "fg:color_shell"

[container]
style = "fg:color_container"
format = '( [$symbol $name]($style) )'

[jobs]
symbol = "󰒋"
style = "fg:color_other"
format = '( [$symbol( $number)]($style) )'
symbol_threshold = 1
number_threshold = 1

[time]
disabled = true
time_format = "%R"
style = "fg:color_time"
format = '( [󰔛 $time]($style) )'

[cmd_duration]
min_time = 2000
format = '( [󱫑 $duration]($style) )'
style = 'fg:color_duration'
show_milliseconds = false
disabled = false

[status]
disabled = false
format = '( [$symbol( $common_meaning)( $signal_name)$pipestatus]($style) )'
map_symbol = true
pipestatus = true
symbol = '󰅙'
success_symbol = ''
not_executable_symbol = '󰂭'
not_found_symbol = '󰍉'
sigint_symbol = '󰐊'
signal_symbol = '󱐋'
style = 'bold fg:color_danger'
recognize_signal_code = true

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_ok)'
error_symbol = '[❯](bold fg:color_danger)'
vimcmd_symbol = '[❮](bold fg:color_vimcmd_ok)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_vimcmd_replace)'
vimcmd_replace_symbol = '[❮](bold fg:color_vimcmd_replace)'
vimcmd_visual_symbol = '[❮](bold fg:color_vimcmd_visual)'

